name: Unit Tests

on:
  push:
    branches: ["**"]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache conda packages
        uses: actions/cache@v3
        with:
          path: /home/runner/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('amd_env.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: amd_env.yml
          activate-environment: amd_env
          auto-activate-base: false
          use-mamba: true
      
      - name: Run pytest
        shell: bash -l {0}
        env:
            PYTHONFAULTHANDLER: "1"
            OMP_NUM_THREADS: "1"
            MKL_NUM_THREADS: "1"
            OPENBLAS_NUM_THREADS: "1"
            NUMEXPR_NUM_THREADS: "1"
            VECLIB_MAXIMUM_THREADS: "1"
        run: |
          export PYTHONPATH="$(pwd):$(pwd)/ml_models:${PYTHONPATH}"
          conda run -n amd_env pytest -s
